// <auto-generated />
using FreyjaBåthuset_WebAPI_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FreyjaBåthuset_WebAPI_Backend.Migrations
{
    [DbContext(typeof(FreyjaBåthuset_WebAPI_BackendContext))]
    partial class FreyjaBåthuset_WebAPI_BackendContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FrejaBåthuset_WebAPI_Backend.Models.BoatTripBooking", b =>
                {
                    b.Property<int>("BoatTripBookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DateTime")
                        .HasColumnType("int");

                    b.Property<int>("DiscoverBoatHouse")
                        .HasColumnType("int");

                    b.Property<string>("OtherActivities")
                        .HasColumnType("string");

                    b.HasKey("BoatTripBookingID");

                    b.ToTable("BoatTripBooking");
                });
#pragma warning restore 612, 618
        }
    }
}
